// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NgrokExtensions
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidStartTunnelPackageString = "9f845cfc-84ef-4aac-9826-d46a83744fb4";
        public static Guid guidStartTunnelPackage = new Guid(guidStartTunnelPackageString);

        public const string guidStartTunnelPackageCmdSetString = "30d1a36d-a03a-456d-b639-f28b9b23e161";
        public static Guid guidStartTunnelPackageCmdSet = new Guid(guidStartTunnelPackageCmdSetString);

        public const string guidImagesString = "53461b84-0d32-4e9f-bd34-4ddb67e572a7";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int StartTunnelId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}